name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        node-version: ['17', '16', '14', '12']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npm run test
      
    - name: Sleep for 1m seconds
      run: sleep 10m
      shell: bash
